apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: prometheus-stack
nodes:
- role: worker
- role: worker
- role: control-plane
  extraPortMappings:
  # Prometheus
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
  # Prometheus Alertmanager
  - containerPort: 9093
    hostPort: 9093
    protocol: TCP
  # Grafana
  - containerPort: 3000
    hostPort: 80
    protocol: TCP
