apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-rook-block-device
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
