apiVersion: v1
kind: Service
metadata:
    name: website
    labels:
      app: website
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
  - nodePort: 30080
    port: 80
    targetPort: 80
