apiVersion: v1
kind: Pod
metadata:
  name: example-rook-ceph-block-static
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: rook-block-device
          mountPath: /srv
  volumes:
    - name: rook-block-device
      persistentVolumeClaim:
        claimName: example-rook-block-device
