apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-rook-block-device
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: example-rook-block-device
