apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-echo-pod
spec:
  replicas: 3                # desired number of pods
  selector:
    app: node-echo
  template:
    metadata:
      labels:
        app: node-echo
    spec:
      containers:
      - name: node-echo-test
        image: node-echo:0.1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: node-echo-service
  labels:
    app: node-echo
spec:
  type: LoadBalancer
  selector:
    app: node-echo
  ports:
    - port: 8080
      targetPort: 8080

