apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: static-config
  labels:
    prometheus: example-prometheus
spec:
  staticConfigs:
    - labels:
        job: promlab
      targets:
        - demo.promlabs.com:10000
        - demo.promlabs.com:10001
        - demo.promlabs.com:10002
